### ISSUE TITLE
Убрать maven-assembly-plugin 

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#1]
Убрать maven-assembly-plugin  и добавить Spring Boot maven plugin.

```
<groupId>org.springframework.boot</groupId>
 <artifactId>spring-boot-maven-plugin</artifactId>
```

**Comment by turaldinio** [comment]
maven-assembly-plugin убран. Вместо него добавил spring-boot-maven-plugin
<img width="604" alt="Screenshot_1" src="https://github.com/turaldinio/ProjectManagementService/assets/65041919/f4ffade6-a5c1-43c1-a32b-a76d08ea70c9">

**Comment by digdesjavaschool** [comment]
build должен быть в app модуле поскольку он по факту собирается в исполняемый jar

**Comment by turaldinio** [comment]
Перенес в app моудль.
https://github.com/turaldinio/ProjectManagementService/blob/e28c07adc5f29e9b56c2a91caa2d657249e857e4/ProjectManagementSystem-app/pom.xml#LL74C3-L85C13
