### ISSUE TITLE
Необходимо подключить логи

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#10]
Нет логов ...

**Comment by turaldinio** [comment]
Подключил логи. Так как вся основная логика приложения находится в сервисном слое, след логировал только сервисные слои + авторизацию
файл конфигурации:
https://github.com/turaldinio/ProjectManagementService/blob/test/ProjectManagementSystem-app/src/main/resources/log4j2.xml
логи записываются в разные файлы:

<img width="300" alt="Screenshot_5" src="https://github.com/turaldinio/ProjectManagementService/assets/65041919/9c9c457f-7b03-4082-a086-b0ea4219d989">

каждый сервис пишет в свою папку. Есть общий лог allServices (подумал, в нем удобнее смотреть хронологию событий. При необходимости, можно посмотреть хронологию конкретного сервиса)

**Comment by digdesjavaschool** [comment]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/6449725d-815c-40d8-922a-79a8ccf1ac85)

А как же SLF4J + у lombok есть аннотация @SLF4J

**Comment by digdesjavaschool** [comment]
+ этого у тебя не будет если будешь аннотацию из ломбок использовать
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/fbfac11a-d5ae-4877-8e23-2184affa5b57)

**Comment by turaldinio** [comment]
Сделал как ты и говорил. Указал Sl4j аннотации над сервисными слоями, и удалил создание Logger вручную 
https://github.com/turaldinio/ProjectManagementService/blob/e28c07adc5f29e9b56c2a91caa2d657249e857e4/ProjectManagementSystem-business/ProjectManagementSystem-service/src/main/java/com/digital/pm/service/impl/EmployeeServiceImpl.java#LL25C1-L28C62
