### ISSUE TITLE
Необходимо сделать описание сервиса в Swagger

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#11]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/5c12c6fd-0ff4-491c-b29d-b6f5119342c2)

Для этого нужно добавить SwaggerConfig

**Comment by turaldinio** [comment]
добавил описание сервиса.
<img width="406" alt="Screenshot_7" src="https://github.com/turaldinio/ProjectManagementService/assets/65041919/b9b3f4e9-c9c0-4059-a9d1-4027452d81c5">

**Comment by digdesjavaschool** [comment]
ок
