### ISSUE TITLE
Необходимо отключить Open Session In View

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#12]
Почитать можно тут: https://habr.com/ru/articles/440734/

**Comment by turaldinio** [comment]
Про session in view почитал. Безболезненно отключил
https://github.com/turaldinio/ProjectManagementService/blob/f9a168ab44311221a61c43cd034f9a858b8beef4/ProjectManagementSystem-app/src/main/resources/application.properties#L12

**Comment by digdesjavaschool** [comment]
ок
