### ISSUE TITLE
Описание параметров запроса в Swagger

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#13]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/95d531d1-f952-4599-a744-87e0574c2bb0)

Данные параметры не документированы, нужно документировать. И лучше не параметрами запроса а в path добавить.

![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/a6771e66-a1d2-4d0f-9941-4356a462174b)

Аналогично тут:

![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/ea14182d-9799-49f4-9170-681ee1c64c46)

**Comment by turaldinio** [comment]
Изменил. Все Long параметры получаются из @PathVariable. +Добавил описание для Long параметров 
<img width="584" alt="Screenshot_8" src="https://github.com/turaldinio/ProjectManagementService/assets/65041919/23c1a1f4-eebe-4315-ba77-cdb3d0d212db">

**Comment by digdesjavaschool** [comment]
ок
