### ISSUE TITLE
Фильтры для запросов DTO и фильтры в слой Dao лучше разделять.

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#14]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/c8714daa-9b4f-4371-aecf-ee89c6cd029c)

![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/94e7fb4b-96b5-43b8-ac5c-2e9d8a58b26c)

![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/09eb55d3-e93c-4915-9781-a02798c59654)

У тебя API может быть один, а внутренние фильтры могут поменяться (добавиться новые параметры для фильтрации, которые для DTO не нужны, и не хотелось бы эти поля добавлять в DTO для фильтрации).

Например вот такое можно было бы добавить во внутренний фильтр:
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/539d1769-6d51-4e21-a932-c9286bd48ded)

**Comment by turaldinio** [comment]
Вот это не до конца понял. У меня если изменится условие фильтрации (добавится поле), я его просто добавлю в taskFilter.... или я чего то недопонимаю(

**Comment by digdesjavaschool** [comment]
Пример. Если пользовательский фильтр для фильтрации, то что вводит пользователь.
А потом у тебя например появляется специфичная логика, например поиск должен осуществлять с по попределенным статусам или при условии с ролевой моделью, и ты начнешь добавлять поля для фильтрации в фильтр для пользовательского фильтра что становится не верным. Поэтому нужен фильтра общий который объединяет фильтр пользовательский и фильтра бизнеслогики. На сервсином слое ты по сути мерджишь то что пришло от пользователя и доп фильтры от бизнес слоя.

**Comment by digdesjavaschool** [comment]
эти фильтры можно добавить в слой DAO.

**Comment by turaldinio** [comment]
Понял, согласен. 
Создал отдельные dao фильтры для запросов в Dao слой
https://github.com/turaldinio/ProjectManagementService/tree/update/ProjectManagementSystem-business/ProjectManagementSystem-repository/src/main/java/com/digital/pm/repository/filter
