### ISSUE TITLE
Поиск осуществляется по точному совпадению

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#15]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/f82b0baf-9a01-4636-82e9-b0108ede4a40)

Нужно чтобы поиск был:
1) Регистронезависмым
2) И мог искать по части слова (%пе%)

**Comment by turaldinio** [comment]
Изменил. Все поиски по фильтрам регистронезависимы, + поиск осуществляется по части слова 
например: login="user"
find login="e" вернет user.
https://github.com/turaldinio/ProjectManagementService/blob/test/ProjectManagementSystem-business/ProjectManagementSystem-repository/src/main/java/com/digital/pm/repository/spec/EmployeeSpecification.java

**Comment by digdesjavaschool** [comment]
ок
