### ISSUE TITLE
Поиск по тексту

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#16]
Нужно добавить в фильтр поле text 

![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/b6cdf6a7-a2e6-4719-9262-b8c85597528e)

Условие которого поиск "или" по всем полям (фамилия, имя, почта и т.п.).
Также регистро независимый и по части слова.

**Comment by turaldinio** [comment]
добавил только для сущности employee...или для всех необходимо добавить?
https://github.com/turaldinio/ProjectManagementService/blob/f9a168ab44311221a61c43cd034f9a858b8beef4/ProjectManagementSystem-business/ProjectManagementSystem-repository/src/main/java/com/digital/pm/repository/spec/EmployeeSpecification.java#LL62C1-L73C1
