### ISSUE TITLE
В Swagger необходимо добавить аутентификацию JWT

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#19]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/0be3cf44-b920-4c8e-b4fa-8ce64923f849)

Хотя бы чтобы можно было ввести JWT токен.

https://stackoverflow.com/questions/59898874/enable-authorize-button-in-springdoc-openapi-ui-for-bearer-token-authentication

**Comment by turaldinio** [comment]
Добавил возможность авторизации по токену в Swagger
![Снимок экрана (67)](https://github.com/turaldinio/ProjectManagementService/assets/65041919/ba8b45e7-cfca-42bd-be5c-872cd6d1166e)
![Снимок экрана (68)](https://github.com/turaldinio/ProjectManagementService/assets/65041919/ec493e48-8896-49f6-8885-c34cb8221cba)

**Comment by digdesjavaschool** [comment]
SwaggerConfig лучше перенести в Web слой

**Comment by turaldinio** [comment]
перенес конфигурацию swagger в web модуль
https://github.com/turaldinio/ProjectManagementService/blob/update/ProjectManagementSystem-web/src/main/java/com/digital/pm/web/controller/swagger/SwaggerConfig.java
