### ISSUE TITLE
Не верный scope для maven библиотек, которые нужны для тестов.

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#2]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/917e288b-65db-4fce-9611-3333a134b45c)

![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/7dbe321a-347c-4662-8e99-ff214fb03daf)

Библиотеки для тестов не должны попасть в итоговую сборку проекта (они же не используются в рантайме, поэтому и не должны быть там).

**Comment by turaldinio** [comment]
Изменил. Все библиотеки для теста имеют scope test

**Comment by digdesjavaschool** [comment]
ok
