### ISSUE TITLE
Формат даты UTC в DTO

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#20]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/525973d7-dbcf-49ff-83b4-6a78c768e5a2)

Необходимо прописать формат даты (UTC) для DTO чтобы передавалось не в timestamp а в формате UTC

смотри JsonFormat

**Comment by turaldinio** [comment]
Изменил, использовал @jsonFormat
https://github.com/turaldinio/ProjectManagementService/blob/f9a168ab44311221a61c43cd034f9a858b8beef4/ProjectManagementSystem-dto/src/main/java/com/digital/pm/dto/task/CreateTaskDto.java#LL34C1-L37C27

**Comment by digdesjavaschool** [comment]
А в каком часовом поясе? + shape

**Comment by turaldinio** [comment]
Добавил shape + вывод часового пояса
https://github.com/turaldinio/ProjectManagementService/blob/update/ProjectManagementSystem-dto/src/main/java/com/digital/pm/dto/task/TaskDto.java
