### ISSUE TITLE
Тесты лучше перенести в сервисный слой

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#21]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/67591305-afb7-45f3-8819-254b6d88136c)

**Comment by turaldinio** [comment]
Перенес все тесты в сервисный слой 
<img width="292" alt="Screenshot_9" src="https://github.com/turaldinio/ProjectManagementService/assets/65041919/117de837-a631-4b2a-aacf-4d3632d7b165">

**Comment by digdesjavaschool** [comment]
ок
