### ISSUE TITLE
Тесты используют PG 15-й версии, а в docker-compose какая?

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#22]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/250bbe24-c4e4-4403-bdef-841d34cee7e4)

**Comment by turaldinio** [comment]
Подправил. В docker-compose теперь тоже версия 15.1
https://github.com/turaldinio/ProjectManagementService/blob/f9a168ab44311221a61c43cd034f9a858b8beef4/docker-compose/docker-compose.yaml#L8

**Comment by digdesjavaschool** [comment]
Ок
