### ISSUE TITLE
Зачем скан всех пакетов?

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#23]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/308dc465-0ad7-4fd9-a744-12d5d96b1962)

У тебя в каждом модуле должен быть скан тех пакетов которые нужны в модуле, и тогда скан по всем пакетам не нужен. Достаточно импортировать конфиги дочерних слоев.

**Comment by turaldinio** [comment]
исправил в https://github.com/turaldinio/ProjectManagementService/issues/4#issuecomment-1586401731
