### ISSUE TITLE
У слушателей Rabbit можно на вход получать уже готовый объект 

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#24]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/849a07f5-6d4b-4575-a893-df0ead6879d7)

Можно упростить, убрав конфвертацию из Message в DTO

Например можно использовать MessageConverter

 @Bean
    public MessageConverter jsonMessageConverter() {
        return new Jackson2JsonMessageConverter();
    }

**Comment by turaldinio** [comment]
Удалил RabbitMessage.Конвертирую при помощи MessageConverter 
https://github.com/turaldinio/ProjectManagementService/blob/6b19cee40321b493db8eb9d812c3fd253263f979/ProjectManagementSystem-business/ProjectManagementSystem-service/src/main/java/com/digital/pm/service/amqp/MessageConsume.java#L34
https://github.com/turaldinio/ProjectManagementService/blob/6b19cee40321b493db8eb9d812c3fd253263f979/ProjectManagementSystem-business/ProjectManagementSystem-service/src/main/java/com/digital/pm/service/amqp/MessageProduce.java#L28
