### ISSUE TITLE
Для создание слушателей лучше использовать bindings

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#25]
Если ты будешь использовать биндинги у тебя автоматически будет создаваться binding , где говориться, что ты очередь с таким то именем биндишь на такой то exchange и на такой то routing-key.

Пример:

 @RabbitListener(containerFactory = "rabbitListenerContainerFactory",
            bindings = @QueueBinding(value = @Queue(value = "${rabbit.queue}"),
                    key = "${rabbit.routing_key}",
                    exchange = @Exchange(value = "${rabbit.exchange}", type = ExchangeTypes.DIRECT)
            ))

+ наименования нужно сделать читаемые, а не my-queue. Так же наименования ключей по назначению а не rabbit.queue (например email.queue или notification.queue)

**Comment by turaldinio** [comment]
Прочитал поподробнее об аннотации RabbitListener. Насколько понял,при такой более детальной конфигурации этой аннотации, у нас создается контейнер с указанными параметрами queue/key/exchange, что позволяет удалить ручное создание бинов queue/exhange
https://github.com/turaldinio/ProjectManagementService/blob/6b19cee40321b493db8eb9d812c3fd253263f979/ProjectManagementSystem-business/ProjectManagementSystem-service/src/main/java/com/digital/pm/service/amqp/MessageConsume.java#LL26C3-L30C15
