### ISSUE TITLE
Лучше вынести в конфиг не через Value роутинг сообщений

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#26]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/4ac6b429-be33-4339-b4b3-2b7b2739c555)

Сделать в конфиге Bean с конфигураций (например NotificationConfig в котором есть поля а сам конфиг замапить через @ConfigurationProperties(prefix =...)

**Comment by turaldinio** [comment]
Конфиги мапятся в https://github.com/turaldinio/ProjectManagementService/blob/6b19cee40321b493db8eb9d812c3fd253263f979/ProjectManagementSystem-business/ProjectManagementSystem-service/src/main/java/com/digital/pm/service/amqp/config/NotificationConfig.java
следовательно эти конфиг.данные получаем уже из объекта 
https://github.com/turaldinio/ProjectManagementService/blob/6b19cee40321b493db8eb9d812c3fd253263f979/ProjectManagementSystem-business/ProjectManagementSystem-service/src/main/java/com/digital/pm/service/amqp/MessageProduce.java#L16
