### ISSUE TITLE
Switch по Enum

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#27]
![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/7fc73aa8-4dbc-4d69-a284-e34572e08818)

Можно же так....

![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/041e3b39-59ce-4d11-8fa0-8d131f3b0218)

+ break вроде не нужен, но лучше проверить.

**Comment by turaldinio** [comment]
без комментариев....
https://github.com/turaldinio/ProjectManagementService/blob/6b19cee40321b493db8eb9d812c3fd253263f979/ProjectManagementSystem-business/ProjectManagementSystem-service/src/main/java/com/digital/pm/service/impl/ProjectServiceImpl.java#LL102C6-L120C10
