### ISSUE TITLE
Content-Type и Accept заголовки

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#3]
В рестах не прописано produces и consumes

![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/210f6672-391d-4c93-8d13-a5243e2f859a)

**Comment by turaldinio** [comment]
Во всех контроллерах прописал consume & produce 
<img width="858" alt="Screenshot_2" src="https://github.com/turaldinio/ProjectManagementService/assets/65041919/34448aa0-603d-4734-8e2e-909184d67184">
