### ISSUE TITLE
Конфигурация приложения не по модулям

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#4]
Конфигурация для слоя работы с данными (DAO) должна быть в DAO слое.  Аналогично и остальные конфигурации.

![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/8ea52571-3f7b-4904-bab4-2da8251064da)

![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/1fcb3992-0c0c-4827-9746-a456624fe3e8)

**Comment by turaldinio** [comment]
Все конфигурации переместил в соответствующие классы
<img width="492" alt="Screenshot_3" src="https://github.com/turaldinio/ProjectManagementService/assets/65041919/c8f93a35-fb77-4787-ae9e-76a6e4fc2110">
<img width="454" alt="Screenshot_4" src="https://github.com/turaldinio/ProjectManagementService/assets/65041919/6873f46f-1fff-4b1c-90d6-ff3b7ce7e240">

**Comment by digdesjavaschool** [comment]
смотри https://github.com/turaldinio/ProjectManagementService/issues/23

**Comment by turaldinio** [comment]
Изменил конфигурацию. Каждый модуль сканирует только необходимые для него пакеты.
app -> контроллеры
https://github.com/turaldinio/ProjectManagementService/blob/e28c07adc5f29e9b56c2a91caa2d657249e857e4/ProjectManagementSystem-app/src/main/java/com/digital/pm/app/ApplicationConfig.java#L9
контроллеры -> сервисы
https://github.com/turaldinio/ProjectManagementService/blob/e28c07adc5f29e9b56c2a91caa2d657249e857e4/ProjectManagementSystem-web/src/main/java/com/digital/pm/web/controller/ControllerConfig.java#L5
сервисы -> репозитории
https://github.com/turaldinio/ProjectManagementService/blob/e28c07adc5f29e9b56c2a91caa2d657249e857e4/ProjectManagementSystem-business/ProjectManagementSystem-service/src/main/java/com/digital/pm/service/config/ServiceConfig.java#L7
