### ISSUE TITLE
Volume можно убрать из docker-compose

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#6]
У тебя БД и так создается, поэтому volume уже излишен.

У тебя указана переменная окружения - POSTGRES_DB=digital, которая говорит какую бд необходимо создать при создании контейнера.

![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/d5f9a6c2-03bd-4427-9ec5-5c02032381e4)

**Comment by turaldinio** [comment]
Да, не обратил внимание. Удалил

**Comment by digdesjavaschool** [comment]
ok
