### ISSUE TITLE
Пользователь может быть без УЗ

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#8]
Стоит проверка на не пустой пароль.

![image](https://github.com/turaldinio/ProjectManagementService/assets/127389573/a94def0f-01d4-493d-add4-c2a853501ed4)

**Comment by turaldinio** [comment]
вынес уд в отдельную бд
https://github.com/turaldinio/ProjectManagementService/blob/f9a168ab44311221a61c43cd034f9a858b8beef4/ProjectManagementSystem-app/src/main/resources/db.changelog/create/create_credential.xml#LL8C1-L24C17

**Comment by digdesjavaschool** [comment]
ok
