### ISSUE TITLE
По хорошему лучше разделить УЗ от сотрудника

### ISSUE THREAD

**Issue by digdesjavaschool** [turaldinio/ProjectManagementService#9]
Т.е. лучше создать модель УЗ (например User в которой будет логин и пароль).

А в Employee сделать связку к User

**Comment by turaldinio** [comment]
Вынес учетные данные в отдельную таблицу
https://github.com/turaldinio/ProjectManagementService/blob/f9a168ab44311221a61c43cd034f9a858b8beef4/ProjectManagementSystem-app/src/main/resources/db.changelog/create/create_credential.xml#LL8C1-L24C17
Сделал связку с Employee
https://github.com/turaldinio/ProjectManagementService/blob/f9a168ab44311221a61c43cd034f9a858b8beef4/ProjectManagementSystem-business/ProjectManagementSystem-model/src/main/java/com/digital/pm/model/Employee.java#LL24C1-L26C73

**Comment by digdesjavaschool** [comment]
ok
